openapi: 3.0.0
info:
  title: Entity Extractir API
  description: Extracts entity and the accompanying sentence from a url or path provided
  version: 0.1.0
servers:
  - url: http://entity-extractor-{provided by Google}.run.app
    description: full url provided by Google Cloud Run service
paths:
  /extract_entities:
    post:
      summary: Returns a list of unique entities extracted
      description: Extracts entities from text in input_link then insert entities and sentences into database table
      requestBody:
        description: url or path to a file
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input_type:
                  type: string
      responses:
        "200": # status code
          description: A JSON array of entities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /query_entities
    get:
      summary: Returns list of unique entities
      description: Query database table to return all unique entities
      responses:
        "200": # status code
          description: A JSON array of entities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /query_sentences
    post:
      summary: Returns list of sentences with entity provided
      description: Query database table to return all sentences where entity was detected
      requestBody:
        description: entity
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                entity:
                  type: string
      responses:
        "200": # status code
          description: A JSON array of sentences
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

